### PR TITLE
Make skip unknown schemas optional

### PR DESCRIPTION
**Pull request by smithtim**
This PR addresses issue #8 by adding an option `skip-unknown-schemas` as suggested there, defaulting to false.

### CODE REVIEW

**Comment by smithtim** [comment]
Does this look good, or do we need to address the code coverage?

**Review by JasonStiefel — APPROVED** [review]
Would be nice to have more coverage, but that shouldn't stop this going through. the functionality is tested.

**Comment by rkaippully** [comment]
I would like to keep coverage as high as possible, preferably above 97%. That's the only way we can make sure we don't introduce regressions. In the current case, it has covered 93.33% of the changes introduced in this PR and there is room for improvement. 

If you go to https://codecov.io/gh/rkaippully/scim-patch/compare/eb360c6365d346a44716045a46eec6febd75a46e...f97b22718bc1a45db23f5e4f4763ebd294bdecdb/diff you can see lines/forms that don't have 100% coverage in yellow or red. BTW, you can run this locally with `lein cloverage` and get the same report.

**Comment by smithtim** [comment]
I ran `lein cloverage` for this branch, but I did not get the same report.  Here is what I got:

```
|-------------------+---------+---------|
|         Namespace | % Forms | % Lines |
|-------------------+---------+---------|
|   scim-patch.core |   98.39 |   99.41 |
| scim-patch.filter |   96.69 |  100.00 |
|  scim-patch.paths |   96.36 |  100.00 |
|-------------------+---------+---------|
|         ALL FILES |   97.75 |   99.63 |
|-------------------+---------+---------|
```

Thus, it seems that the coverage is already above 97%.  Am I missing something?

**Comment by rkaippully** [comment]
Sorry, let me clarify.

There are two coverage metrics tracked here - `codecov/patch` tracks what percentage of lines changed in this PR have test coverage and `codecov/project` tracks what percentage of the total lines in the project have code coverage.

Besides, there is a difference between the output of `lein cloverage` and `codecov`. The former tracks all lines in the source file. The latter omits blank lines, comments etc from the calculation. That's why you are seeing a difference in the numbers.

For now, I'll relax the settings so that this PR can be merged. I am trying to make the situation better in #17 and add some more tests so that the coverage is above 97% (it is arbitrary, but we have to draw the line somewhere).

**Review by rkaippully — APPROVED** [review]

**Comment by smithtim** [comment]
Thanks, Raghu!

**Pull request merged**
